Repository FlaxEngine/FlaxDocs, pull requests merged in 2021-05, with the labels that each got.

#61 Fix spelling mistakes for CPP Index
  manual/scripting/cpp/index.md
Labels: enhancement

#62 Physics section typo clean-up
  manual/physics/character-controller.md
  manual/physics/colliders/collision-data.md
  manual/physics/collisions.md
  manual/physics/index.md
  manual/physics/physics-settings.md
  manual/physics/raycasting.md
  manual/physics/rigid-bodies.md
  manual/physics/triggers.md
Labels: fix, typo

#63 Small typo clean-up for Shaders. Added Output directory for cli access.
  manual/editor/advanced/command-line-access.md
  manual/graphics/shaders/custom-geometry-drawing.md
  manual/graphics/shaders/index.md
Labels: typo

#64 Updated links and the requirements section.
  manual/get-started/requirements.md
Labels: enhancement

#65 Minor fixes to release-policy.md
  manual/contributing/release-policy.md
Labels: fix, typo

#66 intex.md typo
  manual/scripting/cpp/index.md
Labels: typo

#67 Add details to plugins
  manual/scripting/plugins/index.md
  manual/scripting/plugins/plugin-project.md
Labels: enhancement
