Repository FlaxEngine/FlaxDocs, pull requests merged in 2022-09, with the labels that each got.

#84 Fixed typo in editor.md
  manual/get-started/editor.md
Labels: fix

#85 Added required packages for Linux
  manual/scripting/cpp/index.md
Labels: enhancement

#86 Fixes some typo's in terrain documentation
  manual/terrain/index.md
Labels: typo, fix
