Repository FlaxEngine/FlaxDocs, pull requests merged in 2025-06, with the labels that each got.

#185 (Linux) Add a solution when creating new project
  manual/get-started/linux.md
Labels: enhancement, fix

#187 Fix a typo in sdf.md
  manual/graphics/models/sdf.md
Labels: fix

#189 Add documentation on how to get available screen resolutions
  manual/graphics/overview/index.md
Labels: enhancement
